# application.yml
spring:
  application:
    name: batch-script-monitor

  datasource:
    url: jdbc:h2:mem:batchmonitordb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    cache: false

server:
  port: 8080

batch:
  scripts:
    baseDir: ${user.home}/batch-scripts
    defaultScript: default_script.sh
  execution:
    timeout: 3600 # Execution timeout in seconds
    maxConcurrent: 5 # Maximum concurrent executions
  websocket:
    endpoint: /ws
    topic:
      progress: /topic/progress
      console: /topic/console-output
      status: /topic/status
